export const apiEndpoints = {
  updatePassUrl: "/users/",
  forgetPassUrl: "/sendEmail",
  registerApiUrl: "/api/register",
  loginApiUrl: "/api/login",
  getAllBlogs: "/blogs",
  createBlogApiUrl: "/blogs/",
  saveBlogsApiUrl: "/blogs/savedblogs/",
  profileUpdateApiUrl: "/profile",
  publishBlogApiUrl: "/publishBlog",
  likesApiUrl: "/likes",
  saveBLogApiUrl: "/saveblog",
  getSavedBlogsApiUrl: "/usersaved",
  profileCheckingApiUrl: "/profile/check",
  commentsApiUrl: "/comments",
  uploadThumbnailUrl: "/post/blogthumb",
  deleteBlogUrl: "/blogs",
  postWinnerUrl: "/api/winners",
  getWinnerUrl: "/api/winners/current",
  blogSummary: "/summarize",
  profileImageUrl: "/upload/profile-image",
  generateUserBioUrl: "/generateBio",
  getAuthorUrl: "/author",
  likeCommentsUrl: "/comments/like",
  commentReplyUrl: "/comments/reply",
};
