name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env: # 👈 Global envs available for all steps in this job
      REACT_APP_API_URL: "https://aapmorblogsapi-amb7gsgqc2h5ggfq.southindia-01.azurewebsites.net"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install dependencies and build
        run: |
          npm ci
          CI=false npm run build

      - name: Copy routes.json to build
        run: cp routes.json build/ || true

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHFUL_FLOWER_09C2FCA00 }}
          action: "upload"
          app_location: "build"
          output_location: ""
          api_location: "" # leave blank if no Azure Functions API

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHFUL_FLOWER_09C2FCA00 }}
          action: "close"
